# Generated by Django 5.1.5 on 2025-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sessions', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='client',
        ),
        migrations.AddField(
            model_name='session',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='clients.client'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('group', 'Grupal'), ('private', 'Privada')], default='group', max_length=10),
        ),
    ]
