# Generated by Django 5.1.5 on 2025-01-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_package_remove_session_client_session_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sessions_added', models.PositiveIntegerField(default=0)),
                ('sessions_deducted', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_packs', to='clients.client')),
            ],
        ),
    ]
