# Generated by Django 5.1.5 on 2025-01-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_sessionpack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attended',
        ),
        migrations.AddField(
            model_name='session',
            name='attended_clients',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='session',
            name='clients',
            field=models.ManyToManyField(related_name='sessions', to='clients.client'),
        ),
    ]
