# Generated by Django 5.1.5 on 2025-01-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_session_attended_session_attended_clients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='total_sessions',
            new_name='available_slots',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='total_sessions',
            new_name='slot_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='used_sessions',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Paquete Asignado'), ('deduct', 'Clase Asistida')], max_length=10)),
                ('slots', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='clients.client')),
            ],
        ),
    ]
