# Generated by Django 5.1.5 on 2025-01-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_total_sessions_client_available_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
