# Generated by Django 5.1.5 on 2025-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='clients.client'),
        ),
    ]
