# Generated by Django 5.1.5 on 2025-01-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_session_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionPack',
        ),
    ]
