# Generated by Django 5.1.5 on 2025-01-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_cn_dni_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cn_dni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
