# Generated by Django 5.1.5 on 2025-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_attendancelog_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(choices=[('room_201', 'Sala 201'), ('room_301', 'Sala 301')], default='room_1', max_length=10),
        ),
    ]
